import "./globals.css";
import { Noto_Sans_KR } from "next/font/google";

export const metadata = {
  title: "LinkTree",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const inter = Noto_Sans_KR({
  variable: "--font-inter",
  display: "swap",
  subsets: ["latin"],
  weight: "100",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`${inter.variable}`}>
      <body>{children}</body>
    </html>
  );
}
